### ISSUE TITLE
Wrong Ram Size Shown

### ISSUE THREAD

**Issue by cloudrack-ca** [webvirtcloud/webvirtcloud#1]
![image](https://github.com/webvirtcloud/webvirtcloud/assets/145787423/2534fdfe-a26e-438d-89b4-6524a4e86d41)
![image](https://github.com/webvirtcloud/webvirtcloud/assets/145787423/d1cac37c-aff0-473b-87b1-88558009d266)

**Comment by cloudrack-ca** [comment]
this is from a default template btw also LOVING the platform already!!!

**Comment by romanslonov** [comment]
@cloudrack-ca Thank you for contacting us. The issue was fixed in https://github.com/webvirtcloud/webvirtfrontend
