### ISSUE TITLE
[Feature] Add WHMCS Support

### ISSUE THREAD

**Issue by ItsLeon15** [webvirtcloud/webvirtcloud#10]
Would it be possible to add [WHMCS](https://www.whmcs.com/) support into Webvirtcloud. This project is amazing but some integrations would be nice to have as well. The main things that I would like to see added would be automatic user and VM creation, deleting VMs isn't required but is also a nice qol feature.

P.S. Not sure if this is the right place to ask, so please let me know if it's not.

**Comment by retspen** [comment]
Hello, 

We do not plan to support WHMCS. Thanks for understanding.
