### ISSUE TITLE
Building WebVirtCloud Error

### ISSUE THREAD

**Issue by umifly** [webvirtcloud/webvirtcloud#11]
Building WebVirtCloud...
[+] Building 2.7s (9/14)                                                                                                       docker:default
 => [backend internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 109B                                                                                                        0.0s
 => [backend internal] load build definition from Dockerfile.backend                                                                     0.0s
 => => transferring dockerfile: 1.36kB                                                                                                   0.0s
 => [backend internal] load metadata for docker.io/library/python:3.10-alpine                                                            2.2s
 => CANCELED [backend backend-deps 1/8] FROM docker.io/library/python:3.10-alpine@sha256:8a66e74c0581e0c7b8b481fe7f0444b2fd599685d4fb52  0.4s
 => => resolve docker.io/library/python:3.10-alpine@sha256:8a66e74c0581e0c7b8b481fe7f0444b2fd599685d4fb525c1047da4f6f44fdaa              0.1s
 => => sha256:3571273345649a7407482369206f43c7659a4c1da21115b359eb2f1d8a2b29d1 6.28kB / 6.28kB                                           0.0s
 => => sha256:c303524923177661067f7eb378c3dd5277088c2676ebd1cd78e68397bb80fdbf 0B / 3.35MB                                               0.3s
 => => sha256:e853c0f38ea7ee895b324be2572635fb61172c5bb439c16909ff93c5626bf9e3 0B / 624.72kB                                             0.3s
 => => sha256:4e2bf8fadd7561c3865302dcbab4663eb36e0cf6304ff93f509f8805860c96be 0B / 12.29MB                                              0.3s
 => => sha256:8a66e74c0581e0c7b8b481fe7f0444b2fd599685d4fb525c1047da4f6f44fdaa 1.65kB / 1.65kB                                           0.0s
 => => sha256:617c6db3400e3519e6edd5b505296b48ea1bada9cfc47ef57e460e15d6e26e49 1.37kB / 1.37kB                                           0.0s
 => [backend internal] load build context                                                                                                0.4s
 => => transferring context: 1.31MB                                                                                                      0.4s
 => CACHED [backend backend-deps 2/8] RUN apk add --no-cache gcc g++ pango fontconfig ttf-freefont font-noto terminus-font               0.0s
 => CACHED [backend backend-deps 3/8] WORKDIR /requirements                                                                              0.0s
 => CACHED [backend backend-deps 4/8] COPY ./webvirtbackend/requirements/production.txt requirements.txt                                 0.0s
 => ERROR [backend backend-deps 5/8] COPY ./optional-requirements.txt .                                                                  0.0s

 > [backend backend-deps 5/8] COPY ./optional-requirements.txt .:

failed to solve: failed to compute cache key: failed to calculate checksum of ref e58b4abb-d0cf-4640-a21b-95bd15c3878b::ywf3c9bl92kh2wxxk2g249l13: "/optional-requirements.txt": not found

**Comment by umifly** [comment]
my system: debian bookworm aarch64
kernel version:linux 6.7.0

**Comment by retspen** [comment]
Hello,

Fixed. Run `git pull` and try again.

**Comment by umifly** [comment]
Thank for your help, this error has been resolved.
