### ISSUE TITLE
Issue with the update script

### ISSUE THREAD

**Issue by ItsLeon15** [webvirtcloud/webvirtcloud#12]
I tried to run the `./webvirtcloud.sh update` script however one of the containers `webvirtcloud-mariadb` failed with the message `dependency failed to start: container webvirtcloud-mariadb is unhealthy`. This was after I removed all containers so I'm not sure why that is happening.

**Comment by retspen** [comment]
Hello,
Do you have sensetirve data in database? If you don't have you can delete folder `.mysql` and start again. If you need you data you need reset this commit dump data remove `.mysql` update and than import data to database.

**Comment by ItsLeon15** [comment]
Yep that worked. Thanks!
