### ISSUE TITLE
Billing Intergrations?

### ISSUE THREAD

**Issue by cloudrack-ca** [webvirtcloud/webvirtcloud#13]
May i inquire as to what billing integrations are road mapped currently?

Id like to see
- WHMCS 
- Preferably Upmind more found at [upmind.com](https://upmind.com/)

**Comment by retspen** [comment]
Hello,

We don't have plan to support WHMCS and now you can add external script for charging customers. Maybe in the future we will add external billing systems.

**Comment by cloudrack-ca** [comment]
was looking for something simple not whmcs but https://upmind.com @retspen

**Comment by retspen** [comment]
Sorry, but we have no plans to do this in the near future.
