### ISSUE TITLE
Problems with dev environment on testing WebVirtCloud

### ISSUE THREAD

**Issue by cloudrack-ca** [webvirtcloud/webvirtcloud#2]
hello, i come to you today to inform you that i am having some issues with WebVirtCloud. I am hoping you maybe able to assist. 

I have currently setup the backend & frontend 
![image](https://github.com/webvirtcloud/webvirtcloud/assets/145787423/926cb2ef-39fd-417b-80b9-81ef6a0de985)
![image](https://github.com/webvirtcloud/webvirtcloud/assets/145787423/bba12ffd-7a20-4a36-9a50-d8aa7002c050)

Now I want to of course make a VM how can this be done am i missing a component?

Previously i tried https://github.com/webvirtcloud/webvirtcloud stack and on 
```
git submodule init
git submodule update
```

Im not authoriezed, So leading me to install as stated above backend 

(Backend)
- installed docker/docker compose 
- installed and setup had to wait around 1-2-5minutes by the way for the database to take up which will thus then allow the command `docker compose exec backend python3 manage.py migrate` to work which you need to mention in the documentation for some people as they will continue to get an error if they attempt above command without waiting for db to initialize fully.
- after setup i installed frontend

(frontend)
- installed the node using nvm and noticed the node was using version 16 if not mistaken so I opted for `nvm install 16` as this was the default fresh install `v16` was default no need to switch over to it setup `--host` in package.json for `web` also setup `.env.development` configs urls, then went to backend changed password for main user went to front end used password and email and logged in no problem.

now making a vm is the issue at hand, any help at all would mean alot.

also noticed billing integrable situations in WebVirtCloud kind of like a real cloud hosting provider this is really cool and would love to know more about this as well.

**Comment by retspen** [comment]
Hello,

Project still on beta but are hard working on documentations and production release. You can check ansible and find how to configure hypervisor on this URL https://github.com/webvirtcloud/webvirtcompute/tree/master/ansible/compute

Thank for your feedback!!!

**Comment by cloudrack-ca** [comment]
Keeping eyes WIDE OPEN
