### ISSUE TITLE
[Feature Requirement] Deployment without domain name

### ISSUE THREAD

**Issue by spiritLHLS** [webvirtcloud/webvirtcloud#21]
```
. /webvirtcloud.sh env
```

Requires the user to enter the domain name

I don't want to use a domain name and only use an IP address with different ports to display the page that corresponds to your

```
BASE_DOMAIN=webvirtcloud.app
API_DOMAIN=api.webvirtcloud.app
ASSETS_DOMAIN=assets.webvirtcloud.app
CLIENT_DOMAIN=client.webvirtcloud.app
MANAGE_DOMAIN=manage.webvirtcloud.app
CONSOLE_DOMAIN=console.webvirtcloud.app
```

**Comment by ytjoe** [comment]
I don't want to use a domain name either. What should I do？
@retspen

**Comment by retspen** [comment]
Hello, 

Give me some time. I'm working on a new feature right now, when I'm done with it I can focus on this feature.

**Comment by ytjoe** [comment]
ok, thank you

**Comment by TVKain** [comment]
This would be a nice feature, as of now is there a workaround for this ?

**Comment by spiritLHLS** [comment]
Haven't seen any progress on the adaptation for a while

> This would be a nice feature, as of now is there a workaround for this ?

**Comment by retspen** [comment]
Can you to try last release? We moved all setting to one domain or IP address. Let us know if it works. 

Thanks!

**Comment by spiritLHLS** [comment]
I will test later

**Comment by spiritLHLS** [comment]
First, there was no problem during the installation, but the problem appeared after the installation
If I install Controller using the IP address of this server, then it forces HTTPS but shows error reporting SSL_ERROR_INTERNAL_ERROR_ALERT.

**Comment by retspen** [comment]
Caddy doesn't support IP address and self-signed certificate but I added some trick with service [nip.io](https://nip.io/). Added info to README

**Comment by spiritLHLS** [comment]
Can't it support https similar to PVE's default install? Even if the certificate is not secure.

**Comment by retspen** [comment]
This is a limitation of the Caddy revere proxy server. You can use Nginx with self-signed certificates on top of it

**Comment by spiritLHLS** [comment]
I tested using nip.io and everything works fine, but using a pure IPV4 address still forces the https display to be an exception, maybe because I didn't enter an IP address and used the default localhost directly? For the time being I have no other questions or needs, this thread is closed.

**Comment by spiritLHLS** [comment]
As an additional note, the instructions at https://webvirt.cloud/docs/installation/setup-controller are somewhat outdated and need to be updated accordingly.
