### ISSUE TITLE
admin dashboard login issue

### ISSUE THREAD

**Issue by Distancexx** [webvirtcloud/webvirtcloud#22]
Sry, but I encountered a problem. 
When I entered the default credentials: 
· admin@webvirt.cloud
· admin
I still couldn't complete the login request. What's wrong about that?
<img width="451" alt="1" src="https://github.com/user-attachments/assets/71f5430c-f3c2-426e-ac87-b67f24d34f49">
<img width="471" alt="2" src="https://github.com/user-attachments/assets/6e5b8fba-2a5d-4e32-ab61-127cd2cd7f26">

**Comment by Distancexx** [comment]
And in DB, the webvirtcloud.account_user is empty, is this correct?

<img width="380" alt="3" src="https://github.com/user-attachments/assets/445dedf7-d30b-4286-bdea-d62e7df3dcef">

**Comment by retspen** [comment]
Hello, 

You have to try the next command:

```
$ docker compose exec backend python manage.py loaddata initial_data
```

**Comment by Distancexx** [comment]
> Hello,
> 
> You have to try the next command:
> 
> ```
> $ docker compose exec backend python manage.py loaddata initial_data
> ```

Gotcha, it works. Thx!
