### ISSUE TITLE
docker version issue

### ISSUE THREAD

**Issue by catborise** [webvirtcloud/webvirtcloud#23]
hi there is a glicth with docker version

The error: 
Docker version 27.3.1 is not sufficient. Please update Docker to version 25.0.0 or later.

**Comment by retspen** [comment]
Hi,

This is strange because we don't have any restrictions for docker and docker compose version. Can you add more detail?

**Comment by spiritLHLS** [comment]
Maybe the detection needs to be modified, there's something wrong with the way I'm doing it 😀

**Comment by retspen** [comment]
@spiritLHLS  I think yes 😀

**Comment by retspen** [comment]
Fixed, @catborise please check now
