### ISSUE TITLE
Navigating and client's consolse issue

### ISSUE THREAD

**Issue by mrkj93** [webvirtcloud/webvirtcloud#24]
Hi team, 

after update the new env refactor I think we got issues with navigating - whenerver  we f5 or reload it's always saying 404 pange not found. The client cli consolse also can not function as it has.

**Comment by retspen** [comment]
Hello,

Check please now and update Caddyfile from new templates for noVNC (moved all to one domain)

**Comment by mrkj93** [comment]
thanks, 
But actually it's worked with /admin/* only, if I am on /* (for ex https://mydomain//floating-ips) with F5 or reload action, the 404 NF page appears immediately

**Comment by mrkj93** [comment]
thank you, sir

**Comment by mrkj93** [comment]
thank you, sir
