### ISSUE TITLE
The default user password cannot log in

### ISSUE THREAD

**Issue by kylinpan** [webvirtcloud/webvirtcloud#6]
<img width="1220" alt="image" src="https://github.com/webvirtcloud/webvirtcloud/assets/59395357/76d13db1-1e99-4b32-8d1a-b1e6327417eb">

**Comment by retspen** [comment]
Did you run `migrate` and `loaddata` command?

**Comment by kylinpan** [comment]
use docker compose
<img width="655" alt="image" src="https://github.com/webvirtcloud/webvirtcloud/assets/59395357/8334e9c5-0138-4fa9-99e8-e03185bfdd5f">
The user can query in the database
<img width="1093" alt="image" src="https://github.com/webvirtcloud/webvirtcloud/assets/59395357/59a8560d-ae24-407e-84c3-a5afb02f1548">

**Comment by retspen** [comment]
We added installation script and updated documentation try to install from scratch

**Comment by kylinpan** [comment]
ok
