### ISSUE TITLE
if utilizing personal domain for say issues with ssl arise for backend i.e manage.said.domain

### ISSUE THREAD

**Issue by cloudrack-ca** [webvirtcloud/webvirtcloud#8]
if utilizing personal domain for say issues with ssl arise for backend i.e manage.said.domain

I do believe fixing this issue will help alot of people get started easier with testing and pitching in.

**Comment by retspen** [comment]
If you have personal domain you can use cloudflare it works perfectly with self signed ssl

**Comment by cloudrack-ca** [comment]
my guy im using cloudflare ive tried proxied ive tried even zerotrust tunneling nothing....

**Comment by retspen** [comment]
For domain `manage` we had problem and we already fixed it. For your SSL certificate you can use even nginx and to do revers proxy to 80 port on caddy container (I think fast and simple way).
