### ISSUE TITLE
在lean的openwrt上装好后进不去

### ISSUE THREAD

**Issue by mmeiwenlong** [webvirtcloud/webvirtcloud#9]
![image](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/70423ba2-610a-41dc-a96a-bf014ed6865b)
怎么进

**Comment by retspen** [comment]
Can you describe action what you did?

**Comment by retspen** [comment]
A you sure you use right repo?

**Comment by mmeiwenlong** [comment]
看我的过程吧
![QQ截图20231210170745](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/e059fa67-def7-4a31-bcc8-78cb474babb1)
![QQ截图20231210170018](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/521c086e-4d64-4d37-8431-3558516f1f56)
![QQ截图20231210170050](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/f28a8709-4a36-45a0-9d20-e6d874a0
![QQ截图20231210170115](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/41bbcdf1-3e51-457b-a895-fedddfd1b354)
ac75)
![QQ截图20231210170433](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/d77b5bf6-fae8-4bd4-97e1-fb9f42fd4db8)
![QQ截图20231210170453](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/17ed2118-196c-43fd-a680-64e2a59303e2)
![QQ截图20231210170518](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/747652e8-5910-4d6f-952c-183c4f8bc2d5)
![QQ截图20231210170529](https://github.com/webvirtcloud/webvirtcloud/assets/44661424/12035198-89c5-4e37-accc-04ce23bb341f)

**Comment by retspen** [comment]
Sorry, but we don't support iStore
